"use client";

import { useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Check, Plus, RotateCcw, Trash2 } from "lucide-react";
import type { AutosaveStatus } from "@/lib/autosave-controller";
import { convertCriterionType, distributeWeights, normalizeWeightsToHundred, reorderByDisplayOrder, type Decision } from "@/lib/decision-domain";
import { DraftSchema } from "@/lib/decision-validation";
import { useDecisionEditor } from "@/hooks/use-decision-editor";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { StatusBanner } from "@/components/ui/status-banner";
import { ErrorState } from "@/components/ui/error-state";

const steps = ["options", "criteria", "matrix", "preferences", "weights"] as const;
type Step = typeof steps[number];
const labels: Record<Step, string> = { options: "候选方案", criteria: "决策因素", matrix: "对比数据", preferences: "偏好规则", weights: "重要程度" };
const ratings = { "very-poor": "很差", poor: "较差", average: "一般", good: "较好", "very-good": "很好" } as const;
const statusLabels: Record<AutosaveStatus, string> = { saved: "已自动保存", dirty: "有待保存修改", saving: "正在保存…", failed: "保存失败", conflict: "版本冲突" };

export default function StepBuilder() {
  const params = useParams<{ id: string; step: string }>();
  const router = useRouter();
  const step = steps.includes(params.step as Step) ? params.step as Step : "options";
  const editor = useDecisionEditor(params.id, step);
  const { draft, status, message, setMessage, externalChange, conflict, setConflict, draftValid, missing, patch, go, flush, retry, onEditorBlur, loadLatest, continueEditing, loadConflictCurrent, saveCopy } = editor;

  if (!draft) return <ErrorState title={message==="正在加载…"?"正在加载":"无法打开决策"} message={message} onAction={()=>router.push("/")}/>;
  const index = steps.indexOf(step);

  return <main className="min-h-screen bg-background text-foreground" onBlur={event=>onEditorBlur(event.currentTarget,event.relatedTarget)}>
    <header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><button className="flex items-center gap-2 text-sm text-muted-foreground" onClick={()=>router.push("/")}><ArrowLeft size={16}/>返回 DecisionLab</button><div className={`text-sm ${status==="failed"||status==="conflict"?"text-red-700":"text-muted-foreground"}`}>{statusLabels[status]}{status==="failed"&&<Button className="ml-2" size="sm" variant="outline" onClick={()=>void retry()}>重试</Button>}</div></div></header>
    <section className="mx-auto max-w-6xl px-5 py-8">
      <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div className="w-full max-w-xl"><p className="text-sm font-medium text-primary">Decision Builder</p><label className="mt-2 block text-sm font-medium text-muted-foreground">决策名称<Input className="mt-2 h-11 text-lg font-semibold" value={draft.name} maxLength={100} data-error-key="decision-name" onChange={event=>patch(current=>({...current,name:event.target.value}))}/></label><p className="mt-2 text-sm text-muted-foreground">{!draftValid ? "当前输入尚未通过校验，请检查空白名称或非法数字" : missing.length ? `还有 ${missing.length} 项需要完善` : "已满足结果计算条件"}</p></div><nav className="flex flex-wrap gap-2" aria-label="编辑步骤">{steps.map((item,i)=><Button key={item} size="sm" variant={item===step?"default":"outline"} onClick={()=>void go(item)}><span className="mr-1 opacity-70">{i+1}</span>{labels[item]}</Button>)}</nav></div>
      {message&&<StatusBanner tone="warning" className="mt-5">{message}</StatusBanner>}
      {externalChange&&<StatusBanner tone="warning" className="mt-3" actions={externalChange.type==="deleted"?<Button size="sm" onClick={()=>void saveCopy(draft)}>将当前内容另存副本</Button>:<><Button size="sm" variant="outline" onClick={()=>void loadLatest()}>加载最新内容</Button><Button size="sm" variant="ghost" onClick={continueEditing}>继续编辑</Button></>}>{externalChange.type==="deleted"?"当前决策已被其他标签页删除，自动保存已暂停。":"为避免覆盖新的修改，当前页面已暂停自动保存。"}</StatusBanner>}
      <div className="mt-7">{step==="options"&&<OptionsStep draft={draft} patch={patch}/>} {step==="criteria"&&<CriteriaStep draft={draft} patch={patch}/>} {step==="matrix"&&<MatrixStep draft={draft} patch={patch}/>} {step==="preferences"&&<PreferencesStep draft={draft} patch={patch}/>} {step==="weights"&&<WeightsStep draft={draft} patch={patch}/>}</div>
      <div className="mt-6 flex justify-between"><Button variant="outline" disabled={index===0} onClick={()=>void go(steps[index-1])}><ArrowLeft size={16}/>上一步</Button>{index<steps.length-1?<Button onClick={()=>void go(steps[index+1])}>下一步<ArrowRight size={16}/></Button>:<Button disabled={!draftValid||missing.length>0||status==="saving"||status==="failed"||status==="conflict"} onClick={async()=>{if(!DraftSchema.safeParse(draft).success){setMessage("当前输入尚未通过校验，请检查空白名称或非法数字。");return;}if(await flush())router.push(`/decisions/${draft.id}/results`);else setMessage("尚未保存成功，请先处理页面顶部的保存状态。");}}><Check size={16}/>完成并查看结果</Button>}</div>
    </section>
    <AlertDialog open={conflict!==null} onOpenChange={open=>{if(!open)setConflict(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>检测到版本冲突</AlertDialogTitle><AlertDialogDescription>{conflict?.current?"加载最新版会放弃当前编辑；另存副本会保留当前内容，并且不会覆盖其他标签页的新版本。":"原决策已不存在。你可以把当前编辑另存为一份新决策。"}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel onClick={()=>setConflict(null)}>继续检查</AlertDialogCancel>{conflict?.current&&<Button variant="outline" onClick={loadConflictCurrent}>加载最新版本</Button>}<AlertDialogAction onClick={()=>{if(conflict)void saveCopy(conflict.local)}}>当前编辑另存副本</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </main>;
}

function OptionsStep({draft,patch}:{draft:Decision;patch:(update:(current:Decision)=>Decision)=>void}) {
  const add=()=>patch(current=>{if(current.options.length>=10)return current;const id=crypto.randomUUID();return {...current,options:[...current.options,{id,name:`方案 ${current.options.length+1}`,displayOrder:current.options.length}],values:[...current.values,...current.criteria.map(criterion=>({optionId:id,criterionId:criterion.id,value:null}))]};});
  const remove=(id:string)=>patch(current=>({...current,options:current.options.filter(item=>item.id!==id).map((item,index)=>({...item,displayOrder:index})),values:current.values.filter(value=>value.optionId!==id)}));
  return <Card className="p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">候选方案</h2><p className="mt-1 text-sm text-muted-foreground">添加 2–10 个需要比较的方案。</p></div><Button onClick={add} disabled={draft.options.length>=10}><Plus size={16}/>添加方案</Button></div><div className="mt-6 grid gap-4 md:grid-cols-2">{draft.options.map((option,index)=><label className="rounded-xl border p-4 text-sm font-medium" key={option.id}>方案 {index+1}<div className="mt-2 flex gap-2"><Input data-error-key={`option-${option.id}`} value={option.name} onChange={event=>patch(current=>({...current,options:current.options.map(item=>item.id===option.id?{...item,name:event.target.value}:item)}))}/><Button size="icon" variant="ghost" disabled={index===0} onClick={()=>patch(current=>({...current,options:reorderByDisplayOrder(current.options,option.id,-1)}))} aria-label={`上移${option.name}`}><ArrowUp size={16}/></Button><Button size="icon" variant="ghost" disabled={index===draft.options.length-1} onClick={()=>patch(current=>({...current,options:reorderByDisplayOrder(current.options,option.id,1)}))} aria-label={`下移${option.name}`}><ArrowDown size={16}/></Button><Button size="icon" variant="ghost" disabled={draft.options.length<=2} onClick={()=>remove(option.id)} aria-label={`删除${option.name}`}><Trash2 size={16}/></Button></div></label>)}</div></Card>;
}

function CriteriaStep({draft,patch}:{draft:Decision;patch:(update:(current:Decision)=>Decision)=>void}) {
  const [conversion,setConversion]=useState<{id:string;type:"objective"|"subjective"}|null>(null);
  const add=(type:"objective"|"subjective")=>patch(current=>{if(current.criteria.length>=30)return current;const id=crypto.randomUUID();const base={id,name:type==="objective"?"新客观因素":"新主观因素",weight:0,displayOrder:current.criteria.length};const criterion=type==="objective"?{...base,type,direction:"higher" as const,unit:"",preferenceRule:{poor:0,acceptable:50,ideal:100}}:{...base,type,scale:"five-level" as const};return {...current,criteria:[...current.criteria,criterion],values:[...current.values,...current.options.map(option=>({optionId:option.id,criterionId:id,value:null}))]};});
  const confirmConversion=()=>{if(!conversion)return;patch(current=>convertCriterionType(current,conversion.id,conversion.type));setConversion(null);};
  return <><Card className="p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">决策因素</h2><p className="mt-1 text-sm text-muted-foreground">客观因素填写数字，主观因素使用五档评价，最多 30 个。</p></div><div className="flex gap-2"><Button variant="outline" disabled={draft.criteria.length>=30} onClick={()=>add("objective")}><Plus size={16}/>客观因素</Button><Button variant="outline" disabled={draft.criteria.length>=30} onClick={()=>add("subjective")}><Plus size={16}/>主观因素</Button></div></div><div className="mt-6 space-y-3">{draft.criteria.map((criterion,index)=><div className="flex flex-wrap items-center gap-3 rounded-xl border p-4" key={criterion.id}><Input data-error-key={`criterion-${criterion.id}`} className="min-w-48 flex-1" value={criterion.name} onChange={event=>patch(current=>({...current,criteria:current.criteria.map(item=>item.id===criterion.id?{...item,name:event.target.value}:item)}))}/><NativeSelect className="w-28" value={criterion.type} onChange={event=>setConversion({id:criterion.id,type:event.target.value as "objective"|"subjective"})}><NativeSelectOption value="objective">客观</NativeSelectOption><NativeSelectOption value="subjective">主观</NativeSelectOption></NativeSelect><Button size="icon" variant="ghost" disabled={index===0} onClick={()=>patch(current=>({...current,criteria:reorderByDisplayOrder(current.criteria,criterion.id,-1)}))} aria-label={`上移${criterion.name}`}><ArrowUp size={16}/></Button><Button size="icon" variant="ghost" disabled={index===draft.criteria.length-1} onClick={()=>patch(current=>({...current,criteria:reorderByDisplayOrder(current.criteria,criterion.id,1)}))} aria-label={`下移${criterion.name}`}><ArrowDown size={16}/></Button><Button size="icon" variant="ghost" disabled={draft.criteria.length<=1} onClick={()=>patch(current=>({...current,criteria:current.criteria.filter(item=>item.id!==criterion.id).map((item,index)=>({...item,displayOrder:index})),values:current.values.filter(value=>value.criterionId!==criterion.id)}))} aria-label={`删除${criterion.name}`}><Trash2 size={16}/></Button></div>)}</div></Card><AlertDialog open={conversion!==null} onOpenChange={open=>{if(!open)setConversion(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>转换因素类型？</AlertDialogTitle><AlertDialogDescription>转换后，这个因素已填写的所有方案数据会被清空，并改用新类型的默认设置。此操作会随自动保存写入。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel onClick={()=>setConversion(null)}>取消</AlertDialogCancel><AlertDialogAction onClick={confirmConversion}>确认转换并清空旧值</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}

function MatrixStep({draft,patch}:{draft:Decision;patch:(update:(current:Decision)=>Decision)=>void}) { const valueByPair=useMemo(()=>new Map(draft.values.map(value=>[`${value.optionId}:${value.criterionId}`,value])),[draft.values]);return <Card className="overflow-hidden"><div className="p-6"><h2 className="text-xl font-semibold">方案对比数据</h2><p className="mt-1 text-sm text-muted-foreground">逐项填写每个方案在各因素下的表现。</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-muted/60"><tr><th className="p-4 text-left">因素</th>{draft.options.map(option=><th className="p-4 text-left" key={option.id}>{option.name}</th>)}</tr></thead><tbody>{draft.criteria.map(criterion=><tr className="border-t" key={criterion.id}><th className="p-4 text-left">{criterion.name}</th>{draft.options.map(option=>{const item=valueByPair.get(`${option.id}:${criterion.id}`);const errorKey=`value-${option.id}-${criterion.id}`;return <td className="p-4" key={option.id}>{criterion.type==="objective"?<Input data-error-key={errorKey} type="number" value={String(item?.value??"")} onChange={event=>patch(current=>({...current,values:current.values.map(value=>value.optionId===option.id&&value.criterionId===criterion.id?{...value,value:event.target.value===""?null:Number(event.target.value)}:value)}))}/>:<NativeSelect data-error-key={errorKey} value={String(item?.value??"")} onChange={event=>patch(current=>({...current,values:current.values.map(value=>value.optionId===option.id&&value.criterionId===criterion.id?{...value,value:event.target.value as keyof typeof ratings}:value)}))}><NativeSelectOption value="" disabled>请选择</NativeSelectOption>{Object.entries(ratings).map(([value,label])=><NativeSelectOption value={value} key={value}>{label}</NativeSelectOption>)}</NativeSelect>}</td>})}</tr>)}</tbody></table></div></Card>; }

function PreferencesStep({draft,patch}:{draft:Decision;patch:(update:(current:Decision)=>Decision)=>void}) { const objective=draft.criteria.filter(criterion=>criterion.type==="objective");return <Card className="p-6"><h2 className="text-xl font-semibold">偏好规则</h2><p className="mt-1 text-sm text-muted-foreground">为客观因素设置趋势及不满意、可接受、理想三档锚点。</p>{objective.length?<div className="mt-6 space-y-4">{objective.map(criterion=><div className="rounded-xl border p-4" key={criterion.id}><div className="grid gap-3 md:grid-cols-5"><label className="text-sm font-medium">{criterion.name}<NativeSelect className="mt-2" value={criterion.direction} onChange={event=>patch(current=>({...current,criteria:current.criteria.map(item=>item.id===criterion.id&&item.type==="objective"?{...item,direction:event.target.value as "higher"|"lower"}:item)}))}><NativeSelectOption value="higher">越高越好</NativeSelectOption><NativeSelectOption value="lower">越低越好</NativeSelectOption></NativeSelect></label>{(["poor","acceptable","ideal"] as const).map((key,index)=><label className="text-sm font-medium" key={key}>{({poor:"不满意",acceptable:"可接受",ideal:"理想"})[key]}<Input data-error-key={index===0?`preference-${criterion.id}`:undefined} className="mt-2" type="number" value={Number.isFinite(criterion.preferenceRule[key])?criterion.preferenceRule[key]:""} onChange={event=>patch(current=>({...current,criteria:current.criteria.map(item=>item.id===criterion.id&&item.type==="objective"?{...item,preferenceRule:{...item.preferenceRule,[key]:event.target.value===""?Number.NaN:Number(event.target.value)}}:item)}))}/></label>)}<label className="text-sm font-medium">单位<Input className="mt-2" value={criterion.unit??""} onChange={event=>patch(current=>({...current,criteria:current.criteria.map(item=>item.id===criterion.id&&item.type==="objective"?{...item,unit:event.target.value}:item)}))}/></label></div></div>)}</div>:<p className="mt-6 rounded-xl bg-muted p-5 text-sm text-muted-foreground">当前没有客观因素，无需设置偏好锚点。</p>}</Card>; }

function WeightsStep({draft,patch}:{draft:Decision;patch:(update:(current:Decision)=>Decision)=>void}) { const validWeights=draft.criteria.every(item=>Number.isFinite(item.weight));const total=validWeights?draft.criteria.reduce((sum,item)=>sum+item.weight,0):Number.NaN;const equal=()=>patch(current=>{const weights=distributeWeights(current.criteria.length);return {...current,criteria:current.criteria.map((item,index)=>({...item,weight:weights[index]}))};});const normalize=()=>patch(current=>{const weights=normalizeWeightsToHundred(current.criteria.map(item=>item.weight));if(!weights)return current;return {...current,criteria:current.criteria.map((item,index)=>({...item,weight:weights[index]}))};});return <Card className="p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">重要程度</h2><p className="mt-1 text-sm text-muted-foreground">权重无需手工凑满 100%，计算时会自动归一化。</p></div><div className="flex gap-2"><Button variant="outline" onClick={equal}><RotateCcw size={16}/>平均分配</Button><Button variant="outline" disabled={!validWeights||!total} onClick={normalize}>调整到 100%</Button></div></div><div className="mt-6 space-y-3">{draft.criteria.map(criterion=><label className="flex items-center justify-between gap-4 rounded-xl border p-4 text-sm font-medium" key={criterion.id}><span>{criterion.name}</span><span className="flex items-center gap-2"><Input data-error-key={`weight-${criterion.id}`} className="w-28" type="number" min={0} value={Number.isFinite(criterion.weight)?criterion.weight:""} onChange={event=>patch(current=>({...current,criteria:current.criteria.map(item=>item.id===criterion.id?{...item,weight:event.target.value===""?Number.NaN:Number(event.target.value)}:item)}))}/>%</span></label>)}</div><div className="mt-5 text-right text-sm">当前合计：<b>{validWeights?`${total.toFixed(2)}%`:"请补全权重"}</b></div>{validWeights&&!total&&<p className="mt-2 text-right text-sm text-amber-700">合计为 0 时，请使用“平均分配”或手动填写重要程度。</p>}</Card>; }
